# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vw_candidate', '0002_candidate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='recording',
            name='rate',
        ),
        migrations.AddField(
            model_name='rating',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vw_candidate.Recording'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
