# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vw_candidate', '0003_auto_20180322_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='avg_rate',
        ),
    ]
