# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw_candidate', '0004_remove_candidate_avg_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='competency',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
