# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-11 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vw_client_groups', '0002_auto_20180611_1327'),
        ('vw_candidate', '0005_question_competency'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='subclient_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vw_client_groups.SubClientGroup', verbose_name='SubClient Group'),
        ),
    ]
