# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-29 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vw_client_groups', '0006_remove_clientgroup_admins'),
        ('vw_candidate', '0006_candidate_subclient_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='client_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vw_client_groups.ClientGroup', verbose_name='Client Group'),
        ),
    ]
