# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw_candidate', '0007_candidate_client_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='invite_message',
            field=models.TextField(default='', verbose_name='Invite message'),
            preserve_default=False,
        ),
    ]
