# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubClientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sub_client_group_logos')),
                ('logo_position', models.IntegerField(blank=True, choices=[(1, 'only client logo'), (2, 'only right people logo'), (3, 'both')], default=3)),
                ('client_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vw_client_groups.ClientGroup')),
            ],
        ),
    ]
