# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-11 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vw_client_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientgroup',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='General client'),
        ),
        migrations.AddField(
            model_name='subclientgroup',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
