# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 06:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vw_client_groups', '0003_auto_20180611_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientgroup',
            name='companies',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL, verbose_name='Admins of company'),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Name of company'),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Users of company'),
        ),
        migrations.AlterField(
            model_name='subclientgroup',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Department name'),
        ),
        migrations.AlterField(
            model_name='subclientgroup',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Department users'),
        ),
    ]
