# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vw_client_groups', '0005_auto_20180628_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientgroup',
            name='admins',
        ),
    ]
