# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw_client_groups', '0006_remove_clientgroup_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subclientgroup',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='subclientgroup',
            name='logo_position',
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sub_client_group_logos'),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='logo_position',
            field=models.IntegerField(blank=True, choices=[(1, 'only client logo'), (2, 'only right people logo'), (3, 'both')], default=3),
        ),
    ]
