# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-11 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vw_client_groups', '0007_auto_20180807_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('client_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vw_client_groups.ClientGroup', verbose_name='Client Group')),
                ('subclient_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vw_client_groups.SubClientGroup', verbose_name='SubClient Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('limit', models.FloatField(default=5)),
                ('order', models.IntegerField()),
                ('competency', models.CharField(max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vw_jobs.Job', verbose_name='Job')),
            ],
        ),
    ]
