# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-11 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vw_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Jobs',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Questions',
        ),
    ]
