# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-11 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw_jobs', '0003_auto_20181211_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='link',
            field=models.URLField(default='2', max_length=500, verbose_name='Interview link'),
            preserve_default=False,
        ),
    ]
