# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-18 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vw_jobs', '0004_jobs_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='client_group',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='subclient_group',
        ),
    ]
