# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-23 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw_jobs', '0005_auto_20181219_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='competency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
