# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-16 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw_jobs', '0006_auto_20181224_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='limit',
            field=models.FloatField(default=2),
        ),
    ]
