# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-16 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw_jobs', '0007_auto_20190216_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='limit',
            field=models.IntegerField(default=2),
        ),
    ]
