# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizeduser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
