# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vw_client_groups', '0006_remove_clientgroup_admins'),
        ('vw_user', '0002_auto_20180226_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizeduser',
            name='sub_client_group',
        ),
        migrations.AddField(
            model_name='customizeduser',
            name='client_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_group', to='vw_client_groups.ClientGroup'),
        ),
    ]
