# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw_user', '0003_auto_20180628_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetemplate',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
