# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vw_candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('expiry', models.DateTimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vw_candidate.Candidate')),
            ],
        ),
    ]
