# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-15 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vw_question', '0004_auto_20180515_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competency',
            options={'verbose_name': 'Competency', 'verbose_name_plural': 'Competencies'},
        ),
    ]
