# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-16 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vw_question', '0005_auto_20180515_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
