# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-16 12:16
from __future__ import unicode_literals

from django.contrib.auth import get_user_model
from django.db import migrations


def add_user_to_position(apps, schema_editor):
    # We can't import the User model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Position = apps.get_model('vw_question', 'Position')
    User = apps.get_model('vw_user', 'CustomizedUser')
    user = User.objects.first()
    Position.objects.filter(user__isnull=True).update(user=user)


def reverse_changes(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('vw_question', '0006_position_user'),
    ]

    operations = [
        migrations.RunPython(add_user_to_position, reverse_changes),
    ]
